const variants = [
  { name: 'Original', path: '/', desc: '3-column bento grid' },
  { name: 'Compact', path: '/landing/compact', desc: 'Stacked features, multi-col footer' },
  { name: 'Tall', path: '/landing/tall', desc: 'Full-width sections, alternating backgrounds' },
]

export function ComparePage() {
  const headerHeight = 64

  return (
    <div style={{ height: '100vh', overflow: 'hidden', background: '#f1f3ff', fontFamily: "'Inter', sans-serif", display: 'flex', flexDirection: 'column' }}>
      <div style={{ height: headerHeight, flexShrink: 0, background: '#0029c0', color: 'white', padding: '0 32px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ fontSize: 20, fontWeight: 900, letterSpacing: -0.5 }}>Landing Page Variants</h1>
          <p style={{ fontSize: 13, opacity: 0.7 }}>Generated by Google Stitch — LAYOUT variants with EXPLORE creative range</p>
        </div>
        <p style={{ fontSize: 13, opacity: 0.7 }}>Lucid Capture</p>
      </div>
      <div style={{ flex: 1, display: 'flex', gap: 12, padding: 12, minHeight: 0 }}>
        {variants.map((v) => (
          <div key={v.path} style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, borderRadius: 12, overflow: 'hidden', background: 'white', boxShadow: '0 2px 8px rgba(20,27,43,0.1)' }}>
            <div style={{ padding: '8px 16px', background: 'white', borderBottom: '1px solid #e9edff', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexShrink: 0 }}>
              <div>
                <h2 style={{ fontSize: 14, fontWeight: 700 }}>{v.name}</h2>
                <span style={{ fontSize: 11, color: '#757687', fontWeight: 600 }}>{v.desc}</span>
              </div>
              <a href={v.path} target="_blank" rel="noreferrer" style={{ fontSize: 11, color: '#0029c0', fontWeight: 700, textDecoration: 'none' }}>
                Open full ↗
              </a>
            </div>
            <iframe src={v.path} title={v.name} style={{ flex: 1, width: '100%', border: 'none', minHeight: 0 }} />
          </div>
        ))}
      </div>
    </div>
  )
}
