const variants = [
  { name: 'Original', path: '/', desc: '3-column bento grid' },
  { name: 'Compact', path: '/landing/compact', desc: 'Stacked features, multi-col footer' },
  { name: 'Tall', path: '/landing/tall', desc: 'Full-width sections, alternating backgrounds' },
]

export function ComparePage() {
  return (
    <div style={{ minHeight: '100vh', background: '#f1f3ff', fontFamily: "'Inter', sans-serif" }}>
      <div style={{ background: '#0029c0', color: 'white', padding: '24px 32px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ fontSize: 20, fontWeight: 900, letterSpacing: -0.5 }}>Landing Page Variants</h1>
          <p style={{ fontSize: 13, opacity: 0.7 }}>Generated by Google Stitch — LAYOUT variants with EXPLORE creative range</p>
        </div>
        <p style={{ fontSize: 13, opacity: 0.7 }}>Lucid Capture</p>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 24, padding: 32, maxWidth: 1600, margin: '0 auto' }}>
        {variants.map((v) => (
          <div key={v.path} style={{ background: 'white', borderRadius: 16, overflow: 'hidden', boxShadow: '0 8px 32px rgba(20,27,43,0.08)' }}>
            <div style={{ padding: '16px 20px', borderBottom: '1px solid #e9edff', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <h2 style={{ fontSize: 14, fontWeight: 700 }}>{v.name}</h2>
                <span style={{ fontSize: 11, color: '#757687', fontWeight: 600 }}>{v.desc}</span>
              </div>
              <a href={v.path} target="_blank" rel="noreferrer" style={{ fontSize: 11, color: '#0029c0', fontWeight: 700, textDecoration: 'none' }}>
                Open full ↗
              </a>
            </div>
            <iframe src={v.path} title={v.name} style={{ width: '100%', height: 600, border: 'none' }} />
          </div>
        ))}
      </div>
    </div>
  )
}
